#include "jim.h"

#ifdef __AVR_ARCH__
#include <avr/pgmspace.h> // for PROGMEM, memcpy_P
#define GET_WORD_OFFSET(type, id) pgm_read_word_near(WORDS + (2 * ((type) + (id)) + 0))
#define GET_WORD_LENGTH(type, id) pgm_read_word_near(WORDS + (2 * ((type) + (id)) + 1))
#else /* !__AVR_ARCH__ */
#include <string.h> // memcpy()
#define PROGMEM
#define memcpy_P memcpy
#define GET_WORD_OFFSET(type, id) WORDS[2 * ((type) + (id)) + 0]
#define GET_WORD_LENGTH(type, id) WORDS[2 * ((type) + (id)) + 1]
#endif /* __AVR_ARCH__ */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

typedef enum {
  DELIM_SPACE,
  DELIM_COMMA,
  DELIM_AND,
  DELIM_COMMA_AND,
  DELIM_LAST,
} delim_t;

// generated by pack.rb from ./words.yaml
static const char TEXT[] PROGMEM =
  "appropriatelyassertivelyauthoritativelycollaborativelycompellinglycompet"
  "entlycompletelycontinuallyconvenientlycrediblydistinctivelydramaticallyd"
  "ynamicallyefficientlyenergisticallyenthusiasticallyfungiblygloballyholis"
  "ticlyinteractivelyintrinsiclymonotonectallyobjectivelyphosfluorescentlyp"
  "roactivelyprofessionallyprogressivelyquicklyrapidiouslyseamlesslysynergi"
  "sticallyuniquelyactualizeadministrateaggregatearchitectbenchmarkbrandbui"
  "ldcloudifycommunicateconceptualizecoordinatecreatecultivatecustomizedeli"
  "verdeploydevelopdinintermediatedisseminatedriveembracee-enableempowerena"
  "bleengageengineerenhanceenvisioneerevisculateevolveexpediteexploitextend"
  "fabricatefacilitatefashionformulatefostergenerategrowharnessideateimpact"
  "implementincentivizeincubateinstantiateinitiateinnovateintegrateiteratel"
  "everage existingleverage other'smaintainmatrixmaximizemeshmonetizemorphm"
  "yocardinatenegotiatenetworkoptimizeorchestrateparallel taskplagiarizepon"
  "tificatepredominateproductivateproductizepromoteprovide access topursuer"
  "ecaptiualizereconceptualizeredefinere-engineerreintermediatereinventrepu"
  "rposerestorerevolutionizescaleseizesimplifystrategizestreamlinesupplysyn"
  "dicatesynergizesynthesizetargettransformtransitionunderwhelmunleashutili"
  "zevisualizewhiteboard24/724/365accurateadaptivealternativean expanded ar"
  "ray ofB2BB2Cbackendbackward-compatiblebest-of-breedbleeding-edgebricks-a"
  "nd-clicksbusinessclicks-and-mortarclient-basedclient-centeredclient-cent"
  "ricclient-focusedcollaborativecompellingcompetitivecooperativecorporatec"
  "ost effectivecovalentcross functionalcross-mediacross-platformcross-unit"
  "customer directedcustomizedcutting-edgedistinctivedistributeddiversedyna"
  "mice-businesseconomically soundeffectiveefficientemergingempoweredenable"
  "dend-to-endenterpriseenterprise-wideequity investederror-freeethicalexce"
  "llentexceptionalextensibleextensiveflexiblefocusedfrictionlessfront-endf"
  "ully researchedfully testedfunctionalfunctionalizedfungiblefuture-proofg"
  "lobalgo forwardgoal-orientedgranularhigh standards inhigh-payoffhigh-qua"
  "lityhighly efficientholisticimpactfulinexpensiveinnovativeinstalled base"
  "integratedinteractiveinterdependentintermandatedinteroperableintuitiveju"
  "st in timeleading-edgeleveragedlong-term high-impactlow-risk high-yieldm"
  "agneticmaintainablemarket positioningmarket-drivenmission-criticalmultid"
  "isciplinarymultifunctionalmultimedia basednext-generationone-to-oneopen-"
  "sourceoptimalorthogonalout-of-the-boxpandemicparallelperformance basedpl"
  "ug-and-playpremierpremiumprinciple-centeredproactiveprocess-centricprofe"
  "ssionalprogressiveprospectivequalityreal-timereliableresource suckingres"
  "ource maximizingresource-levelingrevolutionaryrobustscalableseamlessstan"
  "d-alonestandardizedstandards compliantstate of the artstickystrategicsup"
  "eriorsustainablesynergistictacticalteam buildingteam driventechnically s"
  "oundtimelytop-linetransparentturnkeyubiquitousuniqueuser-centricuser fri"
  "endlyvalue-addedverticalviralvirtualvisionaryweb-enabledwirelessworld-cl"
  "assworldwideaction itemsalignmentsapplicationsarchitecturesbandwidthbene"
  "fitsbest practicescatalysts for changechannelscloudscollaboration and id"
  "ea-sharingcommunitiescontentconvergencecore competenciescustomer service"
  "datadeliverablese-businesse-commercee-marketse-tailerse-servicesexperien"
  "cesexpertisefunctionalitiesfungibilitygrowth strategieshuman capitalidea"
  "simperativesinfomediariesinformationinfrastructuresinitiativesinnovation"
  "intellectual capitalinterfacesinternal or \"organic\" sourcesleadershiplea"
  "dership skillsmanufactured productsmarketsmaterialsmeta-servicesmethodol"
  "ogiesmethods of empowermentmetricsmindsharemodelsnetworksnichesniche mar"
  "ketsnosqlopportunities\"outside the box\" thinkingoutsourcingparadigmspart"
  "nershipsplatformsportalspotentialitiesprocess improvementsprocessesprodu"
  "ctsquality vectorsrelationshipsresourcesresultsROIscenariosschemasservic"
  "essolutionssourcesstrategic theme areasstoragesupply chainssynergysystem"
  "stechnologiestechnologytesting procedurestotal linkageusersvaluevortalsw"
  "eb-readinessweb servicesforandwhilebyto ,  and , and   "
;
#define TEXT_LEN 4013

static const uint16_t WORDS[] PROGMEM = {
  // adverbs
  0, 13, // adverbs "appropriately"
  13, 11, // adverbs "assertively"
  24, 15, // adverbs "authoritatively"
  39, 15, // adverbs "collaboratively"
  54, 12, // adverbs "compellingly"
  66, 11, // adverbs "competently"
  77, 10, // adverbs "completely"
  87, 11, // adverbs "continually"
  98, 12, // adverbs "conveniently"
  110, 8, // adverbs "credibly"
  118, 13, // adverbs "distinctively"
  131, 12, // adverbs "dramatically"
  143, 11, // adverbs "dynamically"
  154, 11, // adverbs "efficiently"
  165, 14, // adverbs "energistically"
  179, 16, // adverbs "enthusiastically"
  195, 8, // adverbs "fungibly"
  203, 8, // adverbs "globally"
  211, 10, // adverbs "holisticly"
  221, 13, // adverbs "interactively"
  234, 11, // adverbs "intrinsicly"
  245, 14, // adverbs "monotonectally"
  259, 11, // adverbs "objectively"
  270, 17, // adverbs "phosfluorescently"
  287, 11, // adverbs "proactively"
  298, 14, // adverbs "professionally"
  312, 13, // adverbs "progressively"
  325, 7, // adverbs "quickly"
  332, 11, // adverbs "rapidiously"
  343, 10, // adverbs "seamlessly"
  353, 15, // adverbs "synergistically"
  368, 8, // adverbs "uniquely"

  // verbs
  376, 9, // verbs "actualize"
  385, 12, // verbs "administrate"
  397, 9, // verbs "aggregate"
  406, 9, // verbs "architect"
  415, 9, // verbs "benchmark"
  424, 5, // verbs "brand"
  429, 5, // verbs "build"
  434, 8, // verbs "cloudify"
  442, 11, // verbs "communicate"
  453, 13, // verbs "conceptualize"
  466, 10, // verbs "coordinate"
  476, 6, // verbs "create"
  482, 9, // verbs "cultivate"
  491, 9, // verbs "customize"
  500, 7, // verbs "deliver"
  507, 6, // verbs "deploy"
  513, 7, // verbs "develop"
  520, 15, // verbs "dinintermediate"
  535, 11, // verbs "disseminate"
  546, 5, // verbs "drive"
  551, 7, // verbs "embrace"
  558, 8, // verbs "e-enable"
  566, 7, // verbs "empower"
  573, 6, // verbs "enable"
  579, 6, // verbs "engage"
  585, 8, // verbs "engineer"
  593, 7, // verbs "enhance"
  600, 11, // verbs "envisioneer"
  611, 10, // verbs "evisculate"
  621, 6, // verbs "evolve"
  627, 8, // verbs "expedite"
  635, 7, // verbs "exploit"
  642, 6, // verbs "extend"
  648, 9, // verbs "fabricate"
  657, 10, // verbs "facilitate"
  667, 7, // verbs "fashion"
  674, 9, // verbs "formulate"
  683, 6, // verbs "foster"
  689, 8, // verbs "generate"
  697, 4, // verbs "grow"
  701, 7, // verbs "harness"
  708, 6, // verbs "ideate"
  714, 6, // verbs "impact"
  720, 9, // verbs "implement"
  729, 11, // verbs "incentivize"
  740, 8, // verbs "incubate"
  748, 11, // verbs "instantiate"
  759, 8, // verbs "initiate"
  767, 8, // verbs "innovate"
  775, 9, // verbs "integrate"
  784, 7, // verbs "iterate"
  791, 17, // verbs "leverage existing"
  808, 16, // verbs "leverage other's"
  824, 8, // verbs "maintain"
  832, 6, // verbs "matrix"
  838, 8, // verbs "maximize"
  846, 4, // verbs "mesh"
  850, 8, // verbs "monetize"
  858, 5, // verbs "morph"
  863, 12, // verbs "myocardinate"
  875, 9, // verbs "negotiate"
  884, 7, // verbs "network"
  891, 8, // verbs "optimize"
  899, 11, // verbs "orchestrate"
  910, 13, // verbs "parallel task"
  923, 10, // verbs "plagiarize"
  933, 11, // verbs "pontificate"
  944, 11, // verbs "predominate"
  955, 12, // verbs "productivate"
  967, 10, // verbs "productize"
  977, 7, // verbs "promote"
  984, 17, // verbs "provide access to"
  1001, 6, // verbs "pursue"
  1007, 13, // verbs "recaptiualize"
  1020, 15, // verbs "reconceptualize"
  1035, 8, // verbs "redefine"
  1043, 11, // verbs "re-engineer"
  1054, 14, // verbs "reintermediate"
  1068, 8, // verbs "reinvent"
  1076, 9, // verbs "repurpose"
  1085, 7, // verbs "restore"
  1092, 13, // verbs "revolutionize"
  1105, 5, // verbs "scale"
  1110, 5, // verbs "seize"
  1115, 8, // verbs "simplify"
  1123, 10, // verbs "strategize"
  1133, 10, // verbs "streamline"
  1143, 6, // verbs "supply"
  1149, 9, // verbs "syndicate"
  1158, 9, // verbs "synergize"
  1167, 10, // verbs "synthesize"
  1177, 6, // verbs "target"
  1183, 9, // verbs "transform"
  1192, 10, // verbs "transition"
  1202, 10, // verbs "underwhelm"
  1212, 7, // verbs "unleash"
  1219, 7, // verbs "utilize"
  1226, 9, // verbs "visualize"
  1235, 10, // verbs "whiteboard"

  // adjectives
  1245, 4, // adjectives "24/7"
  1249, 6, // adjectives "24/365"
  1255, 8, // adjectives "accurate"
  1263, 8, // adjectives "adaptive"
  1271, 11, // adjectives "alternative"
  1282, 20, // adjectives "an expanded array of"
  1302, 3, // adjectives "B2B"
  1305, 3, // adjectives "B2C"
  1308, 7, // adjectives "backend"
  1315, 19, // adjectives "backward-compatible"
  1334, 13, // adjectives "best-of-breed"
  1347, 13, // adjectives "bleeding-edge"
  1360, 17, // adjectives "bricks-and-clicks"
  1377, 8, // adjectives "business"
  1385, 17, // adjectives "clicks-and-mortar"
  1402, 12, // adjectives "client-based"
  1414, 15, // adjectives "client-centered"
  1429, 14, // adjectives "client-centric"
  1443, 14, // adjectives "client-focused"
  1457, 13, // adjectives "collaborative"
  1470, 10, // adjectives "compelling"
  1480, 11, // adjectives "competitive"
  1491, 11, // adjectives "cooperative"
  1502, 9, // adjectives "corporate"
  1511, 14, // adjectives "cost effective"
  1525, 8, // adjectives "covalent"
  1533, 16, // adjectives "cross functional"
  1549, 11, // adjectives "cross-media"
  1560, 14, // adjectives "cross-platform"
  1574, 10, // adjectives "cross-unit"
  1584, 17, // adjectives "customer directed"
  1601, 10, // adjectives "customized"
  1611, 12, // adjectives "cutting-edge"
  1623, 11, // adjectives "distinctive"
  1634, 11, // adjectives "distributed"
  1645, 7, // adjectives "diverse"
  1652, 7, // adjectives "dynamic"
  1659, 10, // adjectives "e-business"
  1669, 18, // adjectives "economically sound"
  1687, 9, // adjectives "effective"
  1696, 9, // adjectives "efficient"
  1705, 8, // adjectives "emerging"
  1713, 9, // adjectives "empowered"
  1722, 7, // adjectives "enabled"
  1729, 10, // adjectives "end-to-end"
  1739, 10, // adjectives "enterprise"
  1749, 15, // adjectives "enterprise-wide"
  1764, 15, // adjectives "equity invested"
  1779, 10, // adjectives "error-free"
  1789, 7, // adjectives "ethical"
  1796, 9, // adjectives "excellent"
  1805, 11, // adjectives "exceptional"
  1816, 10, // adjectives "extensible"
  1826, 9, // adjectives "extensive"
  1835, 8, // adjectives "flexible"
  1843, 7, // adjectives "focused"
  1850, 12, // adjectives "frictionless"
  1862, 9, // adjectives "front-end"
  1871, 16, // adjectives "fully researched"
  1887, 12, // adjectives "fully tested"
  1899, 10, // adjectives "functional"
  1909, 14, // adjectives "functionalized"
  1923, 8, // adjectives "fungible"
  1931, 12, // adjectives "future-proof"
  1943, 6, // adjectives "global"
  1949, 10, // adjectives "go forward"
  1959, 13, // adjectives "goal-oriented"
  1972, 8, // adjectives "granular"
  1980, 17, // adjectives "high standards in"
  1997, 11, // adjectives "high-payoff"
  2008, 12, // adjectives "high-quality"
  2020, 16, // adjectives "highly efficient"
  2036, 8, // adjectives "holistic"
  2044, 9, // adjectives "impactful"
  2053, 11, // adjectives "inexpensive"
  2064, 10, // adjectives "innovative"
  2074, 14, // adjectives "installed base"
  2088, 10, // adjectives "integrated"
  2098, 11, // adjectives "interactive"
  2109, 14, // adjectives "interdependent"
  2123, 13, // adjectives "intermandated"
  2136, 13, // adjectives "interoperable"
  2149, 9, // adjectives "intuitive"
  2158, 12, // adjectives "just in time"
  2170, 12, // adjectives "leading-edge"
  2182, 9, // adjectives "leveraged"
  2191, 21, // adjectives "long-term high-impact"
  2212, 19, // adjectives "low-risk high-yield"
  2231, 8, // adjectives "magnetic"
  2239, 12, // adjectives "maintainable"
  2251, 18, // adjectives "market positioning"
  2269, 13, // adjectives "market-driven"
  2282, 16, // adjectives "mission-critical"
  2298, 17, // adjectives "multidisciplinary"
  2315, 15, // adjectives "multifunctional"
  2330, 16, // adjectives "multimedia based"
  2346, 15, // adjectives "next-generation"
  2361, 10, // adjectives "one-to-one"
  2371, 11, // adjectives "open-source"
  2382, 7, // adjectives "optimal"
  2389, 10, // adjectives "orthogonal"
  2399, 14, // adjectives "out-of-the-box"
  2413, 8, // adjectives "pandemic"
  2421, 8, // adjectives "parallel"
  2429, 17, // adjectives "performance based"
  2446, 13, // adjectives "plug-and-play"
  2459, 7, // adjectives "premier"
  2466, 7, // adjectives "premium"
  2473, 18, // adjectives "principle-centered"
  2491, 9, // adjectives "proactive"
  2500, 15, // adjectives "process-centric"
  2515, 12, // adjectives "professional"
  2527, 11, // adjectives "progressive"
  2538, 11, // adjectives "prospective"
  2549, 7, // adjectives "quality"
  2556, 9, // adjectives "real-time"
  2565, 8, // adjectives "reliable"
  2573, 16, // adjectives "resource sucking"
  2589, 19, // adjectives "resource maximizing"
  2608, 17, // adjectives "resource-leveling"
  2625, 13, // adjectives "revolutionary"
  2638, 6, // adjectives "robust"
  2644, 8, // adjectives "scalable"
  2652, 8, // adjectives "seamless"
  2660, 11, // adjectives "stand-alone"
  2671, 12, // adjectives "standardized"
  2683, 19, // adjectives "standards compliant"
  2702, 16, // adjectives "state of the art"
  2718, 6, // adjectives "sticky"
  2724, 9, // adjectives "strategic"
  2733, 8, // adjectives "superior"
  2741, 11, // adjectives "sustainable"
  2752, 11, // adjectives "synergistic"
  2763, 8, // adjectives "tactical"
  2771, 13, // adjectives "team building"
  2784, 11, // adjectives "team driven"
  2795, 17, // adjectives "technically sound"
  2812, 6, // adjectives "timely"
  2818, 8, // adjectives "top-line"
  2826, 11, // adjectives "transparent"
  2837, 7, // adjectives "turnkey"
  2844, 10, // adjectives "ubiquitous"
  2854, 6, // adjectives "unique"
  2860, 12, // adjectives "user-centric"
  2872, 13, // adjectives "user friendly"
  2885, 11, // adjectives "value-added"
  2896, 8, // adjectives "vertical"
  2904, 5, // adjectives "viral"
  2909, 7, // adjectives "virtual"
  2916, 9, // adjectives "visionary"
  2925, 11, // adjectives "web-enabled"
  2936, 8, // adjectives "wireless"
  2944, 11, // adjectives "world-class"
  2955, 9, // adjectives "worldwide"

  // nouns
  2964, 12, // nouns "action items"
  2976, 10, // nouns "alignments"
  2986, 12, // nouns "applications"
  2998, 13, // nouns "architectures"
  3011, 9, // nouns "bandwidth"
  3020, 8, // nouns "benefits"
  3028, 14, // nouns "best practices"
  3042, 20, // nouns "catalysts for change"
  3062, 8, // nouns "channels"
  3070, 6, // nouns "clouds"
  3076, 30, // nouns "collaboration and idea-sharing"
  3106, 11, // nouns "communities"
  3117, 7, // nouns "content"
  3124, 11, // nouns "convergence"
  3135, 17, // nouns "core competencies"
  3152, 16, // nouns "customer service"
  3168, 4, // nouns "data"
  3172, 12, // nouns "deliverables"
  3184, 10, // nouns "e-business"
  3194, 10, // nouns "e-commerce"
  3204, 9, // nouns "e-markets"
  3213, 9, // nouns "e-tailers"
  3222, 10, // nouns "e-services"
  3232, 11, // nouns "experiences"
  3243, 9, // nouns "expertise"
  3252, 15, // nouns "functionalities"
  3267, 11, // nouns "fungibility"
  3278, 17, // nouns "growth strategies"
  3295, 13, // nouns "human capital"
  3308, 5, // nouns "ideas"
  3313, 11, // nouns "imperatives"
  3324, 13, // nouns "infomediaries"
  3337, 11, // nouns "information"
  3348, 15, // nouns "infrastructures"
  3363, 11, // nouns "initiatives"
  3374, 10, // nouns "innovation"
  3384, 20, // nouns "intellectual capital"
  3404, 10, // nouns "interfaces"
  3414, 29, // nouns "internal or "organic" sources"
  3443, 10, // nouns "leadership"
  3453, 17, // nouns "leadership skills"
  3470, 21, // nouns "manufactured products"
  3491, 7, // nouns "markets"
  3498, 9, // nouns "materials"
  3507, 13, // nouns "meta-services"
  3520, 13, // nouns "methodologies"
  3533, 22, // nouns "methods of empowerment"
  3555, 7, // nouns "metrics"
  3562, 9, // nouns "mindshare"
  3571, 6, // nouns "models"
  3577, 8, // nouns "networks"
  3585, 6, // nouns "niches"
  3591, 13, // nouns "niche markets"
  3604, 5, // nouns "nosql"
  3609, 13, // nouns "opportunities"
  3622, 26, // nouns ""outside the box" thinking"
  3648, 11, // nouns "outsourcing"
  3659, 9, // nouns "paradigms"
  3668, 12, // nouns "partnerships"
  3680, 9, // nouns "platforms"
  3689, 7, // nouns "portals"
  3696, 14, // nouns "potentialities"
  3710, 20, // nouns "process improvements"
  3730, 9, // nouns "processes"
  3739, 8, // nouns "products"
  3747, 15, // nouns "quality vectors"
  3762, 13, // nouns "relationships"
  3775, 9, // nouns "resources"
  3784, 7, // nouns "results"
  3791, 3, // nouns "ROI"
  3794, 9, // nouns "scenarios"
  3803, 7, // nouns "schemas"
  3810, 8, // nouns "services"
  3818, 9, // nouns "solutions"
  3827, 7, // nouns "sources"
  3834, 21, // nouns "strategic theme areas"
  3855, 7, // nouns "storage"
  3862, 13, // nouns "supply chains"
  3875, 7, // nouns "synergy"
  3882, 7, // nouns "systems"
  3889, 12, // nouns "technologies"
  3901, 10, // nouns "technology"
  3911, 18, // nouns "testing procedures"
  3929, 13, // nouns "total linkage"
  3942, 5, // nouns "users"
  3947, 5, // nouns "value"
  3952, 7, // nouns "vortals"
  3959, 13, // nouns "web-readiness"
  3972, 12, // nouns "web services"

  // joins
  3984, 3, // joins "for"
  3987, 3, // joins "and"
  3990, 5, // joins "while"
  3995, 2, // joins "by"
  3997, 2, // joins "to"

  // delims
  3999, 1, // delims " "
  4000, 2, // delims ", "
  4002, 5, // delims " and "
  4007, 6, // delims ", and "

};

#define ADVERBS 0
#define NUM_ADVERBS 32

#define VERBS 32
#define NUM_VERBS 99

#define ADJECTIVES 131
#define NUM_ADJECTIVES 154

#define NOUNS 285
#define NUM_NOUNS 89

#define JOINS 374
#define NUM_JOINS 5

#define DELIMS 379
#define NUM_DELIMS 4

// stats: total word count: 383
// stats: maximum word length: 30

static uint16_t
jim_unique_random_int(
  jim_sentence_t * const sentence,
  const uint16_t max,
  const uint16_t * const words,
  const uint8_t num_words,
  uint16_t (*random_int)(jim_sentence_t * const, uint16_t, uint16_t)
) {
  uint16_t r;
  
retry:
  r = random_int(sentence, 0, max);

  for (uint8_t i = 0; i < num_words; i++) {
    if (r == words[i]) {
      goto retry;
    }
  }

  // return word
  return r;
}

void
jim_sentence_init(
  jim_sentence_t * const r,
  uint16_t (*random_int)(jim_sentence_t * const, uint16_t, uint16_t),
  void * const user_data
) {
  r->user_data = user_data;
  r->num_phrases = random_int(r, 1, 4);
  for (uint8_t phrase_i = 0; phrase_i < r->num_phrases; phrase_i++) {
    // adverb
    r->phrases[phrase_i].has_adverb = (random_int(r, 0, 2) == 1);
    r->phrases[phrase_i].adverb = random_int(r, 0, NUM_ADVERBS);

    // verb
    r->phrases[phrase_i].verb = random_int(r, 0, NUM_VERBS);

    // adjectives
    r->phrases[phrase_i].num_adjectives = random_int(r, 0, 5);
    for (uint8_t adj_i = 0; adj_i < r->phrases[phrase_i].num_adjectives; adj_i++) {
      // get unique adjective
      r->phrases[phrase_i].adjectives[adj_i] = jim_unique_random_int(
        r,
        NUM_ADJECTIVES,
        r->phrases[phrase_i].adjectives,
        adj_i,
        random_int
      );
    }

    // noun
    r->phrases[phrase_i].noun = random_int(r, 0, NUM_NOUNS);

    if (phrase_i < (r->num_phrases - 1)) {
      // add join word
      r->joins[phrase_i] = jim_unique_random_int(
        r,
        NUM_JOINS,
        r->joins,
        phrase_i,
        random_int
      );
    }
  }
}

static void
send_word(
  const jim_sentence_t * const sentence,
  const uint16_t word_type,
  const uint16_t word_id,
  char * const buf,
  void (*text_cb)(const jim_sentence_t * const, const char * const)
) {
  const uint16_t ofs = GET_WORD_OFFSET(word_type, word_id),
                 len = GET_WORD_LENGTH(word_type, word_id);

  // populate/terminate buffer
  memcpy_P(buf, TEXT + ofs, len);
  buf[len] = '\0';

  // send word
  text_cb(sentence, buf);
}

static void
send_delim(
  const jim_sentence_t * const sentence,
  const delim_t delim,
  char * const buf,
  void (*text_cb)(const jim_sentence_t * const, const char * const)
) {
  send_word(sentence, DELIMS, delim, buf, text_cb);
}

static void
jim_phrase_emit(
  const jim_sentence_t * const sentence,
  const jim_phrase_t * const phrase,
  char * const buf,
  void (*text_cb)(const jim_sentence_t * const, const char * const)
) {
  // adverb
  if (phrase->has_adverb) {
    // send adverb, send space
    send_word(sentence, ADVERBS, phrase->adverb, buf, text_cb);
    send_delim(sentence, DELIM_SPACE, buf, text_cb);
  }

  // verb
  {
    // send verb, send space
    send_word(sentence, VERBS, phrase->verb, buf, text_cb);
    send_delim(sentence, DELIM_SPACE, buf, text_cb);
  }

  // adjectives
  for (uint8_t i = 0; i < phrase->num_adjectives; i++) {
    // send adjective
    send_word(sentence, ADJECTIVES, phrase->adjectives[i], buf, text_cb);

    if (phrase->num_adjectives == 1) {
      // send tail space
      send_delim(sentence, DELIM_SPACE, buf, text_cb);
    } else if (phrase->num_adjectives == 2) {
      if (i == 0) {
        // send delimiting " and "
        send_delim(sentence, DELIM_AND, buf, text_cb);
      } else {
        // send tail " "
        send_delim(sentence, DELIM_SPACE, buf, text_cb);
      }
    } else if (phrase->num_adjectives > 2) { 
      if (i == phrase->num_adjectives - 2) {
        // send ", and " before final adjective
        send_delim(sentence, DELIM_COMMA_AND, buf, text_cb);
      } else if (i < phrase->num_adjectives - 2) {
        // send delimiting ", "
        send_delim(sentence, DELIM_COMMA, buf, text_cb);
      } else {
        // send tail " "
        send_delim(sentence, DELIM_SPACE, buf, text_cb);
      }
    }
  }

  // send noun
  send_word(sentence, NOUNS, phrase->noun, buf, text_cb);
}

void
jim_sentence_emit(
  const jim_sentence_t * const sentence,
  char * const buf,
  void (*text_cb)(const jim_sentence_t * const, const char * const)
) {
  for (uint8_t i = 0; i < sentence->num_phrases; i++) {
    jim_phrase_emit(sentence, sentence->phrases + i, buf, text_cb);

    // send join word
    if (sentence->num_phrases > 1 && i < (sentence->num_phrases - 1)) {
      // send space, join, space
      send_delim(sentence, DELIM_SPACE, buf, text_cb);
      send_word(sentence, JOINS, sentence->joins[i], buf, text_cb);
      send_delim(sentence, DELIM_SPACE, buf, text_cb);
    }
  }
}

void *
jim_sentence_get_data(
  const jim_sentence_t * const sentence
) {
  return sentence->user_data;
}

#ifdef __cplusplus
};
#endif /* __cplusplus */
